### ISSUE TITLE
Issue with scaffolding with HiRise trough docker container

### ISSUE THREAD

**Issue by LeoVincenzi** [aakashsur/docker-hirise#1]
Hi,
I am working on a plant genome assembly in which I’m trying to perform scaffolding with HiRise. I have noticed that the GitHub page of the software is really old and that for your work, you have created a docker container that made all the tried software available.

Actually, I’m facing some issues using HiRise: while the docker pulls command run without problems, the docker run arrives at an end but with many errors in the standard output and without producing the final .srf file. Inside the standard output, I have found many times as possible origin of the problem the following error:

Traceback (most recent call last):
  File "/root/docker-hirise/scripts/window_stats.py", line 51, in <module>
    raise e
  File "/root/docker-hirise/scripts/window_stats.py", line 47, in <module>
    asf.window_stats(c,a,b,debug=args.debug,bins=args.bin)
  File "/root/docker-hirise/scripts/hirise_assembly.py", line 526, in window_stats
    top2 = self.top_other_contigs(reference,mapq=mapq,debug=debug,bins=bins,binx=binx)
  File "/root/docker-hirise/scripts/hirise_assembly.py", line 502, in top_other_contigs
    if BamTags.mate_mapq(aln) < mapq : continue
TypeError: '<' not supported between instances of 'type' and 'int'   

From what I understand, it seems it is due to some issue with the python version (my default one is the 3.8.8).
Do you have any suggestions about it? Is it a problem you’ve already faced before?

The bam is sorted and indexed with samtools and the command I run is 
`docker run --rm --volume $PWD:/root/results --workdir /root/results aakashsur/hirise hirise Hi-C_reads_on_assembly.sorted.bam genome.fasta`

**Comment by aakashsur** [comment]
Okay I believe the BAM file is missing the appropriate mate tags. HiRise checks for the MQ tag, which provides the MAPQ score of the paired mate. In order to add this you need to run your alignment with samblaster. Here is the workflow that I typically use. 

```
# Alignment 
bwa mem \
    -SP5 \
    -t num_cores \
    index.fasta \
    read_1.fastq.gz \
    read_2.fastq.gz | \
samblaster \
    --addMateTags > \
    alignment.sam

# Remove unmapped reads, reads without mapped mates, and secondary alignments. 
samtools view \
    -h \
    -@ num_cores \
    -F 3340 \
    -o filtered.sam \
    alignment.sam

# Coordinate sort. 
samtools sort \
    -@ num_cores \
    -m mem_per_core \
    -o filtered_sort.bam \
    filtered.sam

# Index the sort.
samtools index \
    -@ num_cores \
    filtered_sort.bam

```

**Comment by aakashsur** [comment]
Was this able to fix the problem?

**Comment by LeoVincenzi** [comment]
Hi @aakashsur, sorry but it takes me a while to perform the scaffolding due to other stuff.
Everything seems to have worked well. I got now my hirise.srf file which contains an output like this:
```
1       CONTIG1 +tig00001254_pilon_pilon_pilon_1        0       42060   20.0
2       CONTIG1 -tig00001111_pilon_pilon_pilon_1        0       68487   20.0
3       CONTIG1 +tig00002006_pilon_pilon_pilon_1        0       16727   20.0
4       CONTIG1 -tig00000071_pilon_pilon_pilon_1        0       44958   20.0
5       CONTIG1 -tig00000561_pilon_pilon_pilon_1        0       537450  20.0
6       CONTIG1 -tig00000208_pilon_pilon_pilon_1        0       34325   20.0
7       CONTIG1 -tig00000954_pilon_pilon_pilon_1        0       73167   20.0
8       CONTIG1 +tig00002117_pilon_pilon_pilon_1        0       23818   20.0
9       CONTIG1 +tig00001596_pilon_pilon_pilon_1        0       25145   20.0
...
```
Actually, I was wondering what is the header of this file, so what each column stands for. Moreover, I don't understand how to obtain a fasta file with the assembled sequences from this file.
If you could give me any clue, I would be really grateful!

**Comment by aakashsur** [comment]
Okay that's great to hear, I use some additional processing scripts for HiRise since it doesn't output a fasta file and the output isn't an AGP file. The first step is to convert the hirise.srf file into an agp file and I use [this script](https://github.com/Noble-Lab/hic_scaffolder_benchmarks/blob/master/main/scaffolding/hirise.py) and [this script](https://github.com/Noble-Lab/hic_scaffolder_benchmarks/blob/master/main/utils/agp.py) (you'll notice the import statement at the top of `hirise.py`). And then convert the agp file into a scaffolded fasta file using the original fasta file with [this script](https://github.com/Noble-Lab/hic_scaffolder_benchmarks/blob/master/main/utils/fasta.py). 

The overall structure looks something like this for me 
```
# Run scaffolding.
singularity run \
    --bind $PWD:/root/results \
    --home $PWD:/root/results \
    {hirise_path} \
    hirise \
    alignment.bam \
    assembly.fasta

# Get AGP.
python {main_directory}/scaffolding/hirise.py \
    --input hirise.srf \
    --output {results_directory}/{project_name}_hirise.agp

# Make FASTA from AGP. 
python {main_directory}/utils/fasta.py \
    --input {assembly_file} \
    --agp {results_directory}/{project_name}_hirise.agp \
    --output {results_directory}/{project_name}_hirise.fasta

```

**Comment by LeoVincenzi** [comment]
Great! Now I got my assembled genome. Thank you again for your support!
